-- AlterTable
ALTER TABLE "cotizacion" ADD COLUMN     "completada" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "tipoSeguro" TEXT NOT NULL DEFAULT 'Terceros',
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
